### ISSUE TITLE
Not working with angular

### ISSUE THREAD

**Issue by krishnaradical** [getoutreach/clientxtsdk#43]
I integrate @outreach/client-addon-sdk in angular and  I call  `addonSdk.onInit` function and print  console but console not showing in console.

`  addonSdk.onInit = () => {
      console.log('sa')
   }`

I  am using angular 10 and windows 10.

**Comment by sevcikmartin** [comment]
Hi Krishna,
You need to launch `addonSdk.ready();`
You can find more details in our [SDK documentation](https://github.com/getoutreach/clientxtsdk/blob/master/docs/sdk.md#ready-function).
